using UnityEngine;

public class MouseLook : MonoBehaviour
{
    public float mouseSensitivity = 100f;
    public Transform playerBody;
    private float xRotation = 0f;

    void Start()
    {
        // lock cursor
        Cursor.lockState = CursorLockMode.Locked;
    }

    void Update()
    {
        // mouse listener
        float mouseX = Input.GetAxis("Mouse X") * mouseSensitivity * Time.deltaTime;
        float mouseY = Input.GetAxis("Mouse Y") * mouseSensitivity * Time.deltaTime;

        // up and down rotation
        xRotation -= mouseY;
        xRotation = Mathf.Clamp(xRotation, -90f, 90f);

        // apply
        transform.localRotation = Quaternion.Euler(xRotation, 0f, 0f);

        // rotate player body to match rotation of camera on X plane
        playerBody.Rotate(Vector3.up * mouseX);
    }
}